"""
The Flow Matching layer — Stage 2's core.

A velocity network :math:`v_\\theta(z, t)` learns to transport a frozen image feature toward
its class prototype. At inference the feature is moved by ``T`` Euler steps and the result is
classified with Stage 1's unchanged cosine rule, so the *only* thing that differs from the
Stage 1 prototype baseline is the transport step.

Two training objectives
-----------------------
**Standard FM** supervises the velocity at random points on the ideal straight path::

    t ~ U(0, 1),  z_t = (1 - t) z_i + t p_yi,  u_i = p_yi - z_i
    L_FM = || v(z_t, t) - u_i ||^2

**Rolled-out FM** runs the same ``T``-step rollout used at inference and supervises only
where the feature ends up::

    L_roll = || z_T - p_yi ||^2

The difference that matters: standard FM only ever sees points on the ideal interpolation,
but at inference the network is fed states generated by its *own* previous predictions. If it
drifts off the ideal path, nothing in its training taught it how to recover. Rolled-out
training removes that train/inference mismatch by backpropagating through the whole rollout —
at the cost of ``T`` times the compute per step.

Everything here operates on **L2-normalized** features. Step 1 measured why: with raw features
(norms 24-50) against unit-norm prototypes, the target ``u = p - z`` is 99.99% aligned with
``-z``, so the prototype carries essentially no signal.

Why gradient clipping
---------------------
Backpropagating through ``T`` composed Euler steps can amplify gradients, and without
clipping the rolled-out objective occasionally produces a late-training loss spike that a
fixed-budget run has no way to recover from or ignore. Gradient-norm clipping at 1.0 is
applied here for numerical stability — and applied to **both** objectives, not just the one
that needs it, so the two remain configuration-identical and the comparison still isolates
the objective rather than the tuning.

Why no validation-based checkpointing
-------------------------------------
Stage 1's linear probe selected the best epoch by validation accuracy. That is deliberately
*not* done here. The two objectives are on different scales and measure different things
(velocity error vs. endpoint distance), so there is no single validation quantity that could
select fairly between them. A fixed epoch budget, held identical across both, keeps the
comparison about the objective rather than about a selection rule, so the main training
choices stay fixed between them. Training curves are recorded so stability can be verified
directly.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field

import torch
import torch.nn as nn

from cvlab.prototypes import l2_normalize

__all__ = [
    "FlowConfig",
    "FlowResult",
    "VelocityNet",
    "euler_rollout",
    "classify_by_prototype",
    "train_standard_fm",
    "train_rolled_out_fm",
    "evaluate_flow",
]


@dataclass(frozen=True)
class FlowConfig:
    """Training and architecture settings, held fixed across both objectives.

    Deliberately a small, untuned MLP. These settings mirror Stage 1's probe configuration
    where they overlap (AdamW, lr 1e-3, weight decay 1e-4, batch size 64) rather than
    introducing new numbers to justify.
    """

    hidden_dim: int = 512
    n_hidden: int = 2
    lr: float = 1e-3
    weight_decay: float = 1e-4
    batch_size: int = 64
    epochs: int = 100
    optimizer: str = "AdamW"
    max_grad_norm: float = 1.0

    def as_dict(self) -> dict:
        return {
            "hidden_dim": self.hidden_dim,
            "n_hidden": self.n_hidden,
            "activation": "SiLU",
            "optimizer": self.optimizer,
            "learning_rate": self.lr,
            "weight_decay": self.weight_decay,
            "batch_size": self.batch_size,
            "epochs": self.epochs,
            "max_grad_norm": self.max_grad_norm,
            "checkpoint_selection": "none - final epoch, fixed budget",
        }


@dataclass
class FlowResult:
    """Everything one trained flow model produces."""

    test_acc: dict[int, float]              # T -> top-1 accuracy on the test split
    test_preds: dict[int, torch.Tensor]     # T -> (N_test,) int64 predictions, on CPU
    history: list[float] = field(default_factory=list)   # mean training loss per epoch
    final_loss: float = 0.0
    n_train: int = 0
    n_params: int = 0
    elapsed_s: float = 0.0


class VelocityNet(nn.Module):
    """The velocity field :math:`v_\\theta(z, t)`.

    A plain MLP: scalar time is concatenated to the feature, two SiLU-activated hidden layers
    follow, and the output has the same dimension as the input feature so it can be added
    straight onto the state during integration.

    Args:
        dim: feature dimensionality (512 for ResNet-18, 384 for DINOv2).
        hidden_dim: width of each hidden layer.
        n_hidden: number of hidden layers.
    """

    def __init__(self, dim: int, hidden_dim: int = 512, n_hidden: int = 2) -> None:
        super().__init__()
        self.dim = dim

        layers: list[nn.Module] = []
        in_features = dim + 1                       # +1 for the scalar time
        for _ in range(n_hidden):
            layers += [nn.Linear(in_features, hidden_dim), nn.SiLU()]
            in_features = hidden_dim
        layers += [nn.Linear(in_features, dim)]

        self.net = nn.Sequential(*layers)

    def forward(self, z: torch.Tensor, t: torch.Tensor) -> torch.Tensor:
        """Predict the velocity at state ``z`` and time ``t``.

        Args:
            z: states, shape ``(N, D)``.
            t: times. Accepts a scalar, ``(N,)`` or ``(N, 1)`` — all three occur naturally
                (a fixed step time during rollout, one random draw per example during
                standard FM training), so normalising the shape here keeps every call site
                free of reshaping noise.

        Returns:
            Velocities, shape ``(N, D)``.
        """
        if t.dim() == 0:
            t = t.expand(z.shape[0])
        if t.dim() == 1:
            t = t.unsqueeze(1)
        return self.net(torch.cat([z, t], dim=1))


def euler_rollout(
    net: VelocityNet,
    z0: torch.Tensor,
    T: int,
    return_trajectory: bool = False,
) -> torch.Tensor | tuple[torch.Tensor, torch.Tensor]:
    """Integrate the velocity field with ``T`` uniform Euler steps.

    Implements ``z_{k+1} = z_k + (1/T) v(z_k, k/T)`` for ``k = 0 .. T-1``. Used unchanged
    for inference and inside rolled-out training, which is the point: the two must not
    drift apart, or the "no train/inference mismatch" claim stops being true.

    No ``torch.no_grad()`` here — rolled-out training needs to backpropagate through the
    entire sequence. Callers that only evaluate should wrap the call themselves.

    Args:
        net: the velocity network.
        z0: starting states, shape ``(N, D)``.
        T: number of Euler steps.
        return_trajectory: also return every intermediate state, for the flow-trajectory
            visualisation in step 5.

    Returns:
        ``z_T`` of shape ``(N, D)``, or ``(z_T, trajectory)`` where trajectory has shape
        ``(N, T + 1, D)`` and includes both endpoints.
    """
    if T < 1:
        raise ValueError(f"T must be >= 1, got {T}")

    z = z0
    states = [z0] if return_trajectory else None

    for k in range(T):
        t = torch.full((z.shape[0],), k / T, device=z.device, dtype=z.dtype)
        z = z + net(z, t) / T
        if states is not None:
            states.append(z)

    if states is not None:
        return z, torch.stack(states, dim=1)
    return z


def classify_by_prototype(z: torch.Tensor, prototypes: torch.Tensor) -> torch.Tensor:
    """Stage 1's classification rule, unchanged: ``argmax_c cos(z, mu_c)``.

    The transported feature ``z_T`` is *not* unit-norm — the flow adds unconstrained velocity
    vectors — so it must be normalized before the dot product is a cosine. Prototypes are
    already unit-norm by construction.
    """
    return (l2_normalize(z) @ prototypes.T).argmax(dim=1)


def _mse_per_example(a: torch.Tensor, b: torch.Tensor) -> torch.Tensor:
    """Mean over the batch of the **squared L2 norm** per example.

    Written out rather than using ``F.mse_loss`` because both objectives are stated as
    ``|| . ||_2^2``, and ``mse_loss`` would additionally divide by the feature dimension —
    a 384x or 512x rescale of the loss. Adam largely absorbs a constant factor, but the
    reported loss values would no longer match the formulas being compared.
    """
    return ((a - b) ** 2).sum(dim=1).mean()


def _prepare(
    train_x: torch.Tensor,
    train_y: torch.Tensor,
    prototypes: torch.Tensor,
    device: str,
    seed: int,
    config: FlowConfig,
    normalize: bool = True,
) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor, VelocityNet,
           torch.optim.Optimizer, torch.Generator]:
    """Shared setup for both training loops.

    Keeping this in one place is what guarantees the two objectives get identical
    initialisation, identical batch order and identical normalisation for a given seed — so a
    difference in results is attributable to the objective and nothing else.

    Args:
        normalize: L2-normalize the input features. ``True`` everywhere in the reported
            results; ``False`` exists so the decision can be *ablated* rather than asserted
            (see step 2's normalisation ablation).
    """
    torch.manual_seed(seed)
    if device.startswith("cuda"):
        torch.cuda.manual_seed_all(seed)

    z = (l2_normalize(train_x) if normalize else train_x).to(device)
    y = train_y.to(device)
    p = prototypes.to(device)

    net = VelocityNet(z.shape[1], config.hidden_dim, config.n_hidden).to(device)
    optimizer = torch.optim.AdamW(net.parameters(), lr=config.lr,
                                  weight_decay=config.weight_decay)
    generator = torch.Generator().manual_seed(seed)      # batch order, CPU-side
    return z, y, p, net, optimizer, generator


def train_standard_fm(
    train_x: torch.Tensor,
    train_y: torch.Tensor,
    prototypes: torch.Tensor,
    seed: int,
    config: FlowConfig | None = None,
    device: str = "cuda",
    normalize: bool = True,
) -> tuple[VelocityNet, list[float], float]:
    """Train the velocity network with the standard flow-matching objective.

    For each example a single time ``t ~ U(0, 1)`` is drawn per gradient step, the state is
    placed on the straight line between the (normalized) feature and its prototype, and the
    network is asked to predict the constant velocity of that line.

    Note there is **no** ``T`` here: standard FM never rolls out during training, so one
    trained model is evaluated at every ``T`` of interest.

    Args:
        normalize: L2-normalize inputs. ``False`` only for the normalisation ablation.

    Returns:
        ``(net, history, elapsed_s)`` — history is the mean loss per epoch.
    """
    config = config or FlowConfig()
    z, y, p, net, optimizer, generator = _prepare(
        train_x, train_y, prototypes, device, seed, config, normalize)

    n_train = z.shape[0]
    target_p = p[y]                                     # each example's own prototype
    history: list[float] = []
    start = time.perf_counter()

    for _ in range(config.epochs):
        net.train()
        order = torch.randperm(n_train, generator=generator).to(device)
        running = torch.zeros((), device=device)

        for i in range(0, n_train, config.batch_size):
            idx = order[i:i + config.batch_size]
            z_i, p_i = z[idx], target_p[idx]

            t = torch.rand(idx.numel(), device=device, dtype=z.dtype)
            z_t = (1 - t).unsqueeze(1) * z_i + t.unsqueeze(1) * p_i
            u_i = p_i - z_i

            optimizer.zero_grad(set_to_none=True)
            loss = _mse_per_example(net(z_t, t), u_i)
            loss.backward()
            nn.utils.clip_grad_norm_(net.parameters(), config.max_grad_norm)
            optimizer.step()

            running += loss.detach() * idx.numel()

        history.append((running / n_train).item())

    return net, history, time.perf_counter() - start


def train_rolled_out_fm(
    train_x: torch.Tensor,
    train_y: torch.Tensor,
    prototypes: torch.Tensor,
    T: int,
    seed: int,
    config: FlowConfig | None = None,
    device: str = "cuda",
    normalize: bool = True,
) -> tuple[VelocityNet, list[float], float]:
    """Train the velocity network by backpropagating through the full ``T``-step rollout.

    The network is identical and the rollout is the same :func:`euler_rollout` used at
    inference; only the objective changes — the loss is the squared distance between the
    *final* transported feature and the target prototype, with no supervision on the
    intermediate velocities.

    ``T`` is part of the trained model here (unlike standard FM), so a separate model is
    needed for each ``T`` to be evaluated.

    Args:
        normalize: L2-normalize inputs. Mirrors :func:`train_standard_fm` so the two
            objectives keep identical knobs — the training choices are meant to stay fixed
            between them, and a flag present on only one is a way for that to quietly stop
            being true.

    Returns:
        ``(net, history, elapsed_s)`` — history is the mean loss per epoch.
    """
    config = config or FlowConfig()
    z, y, p, net, optimizer, generator = _prepare(
        train_x, train_y, prototypes, device, seed, config, normalize)

    n_train = z.shape[0]
    target_p = p[y]
    history: list[float] = []
    start = time.perf_counter()

    for _ in range(config.epochs):
        net.train()
        order = torch.randperm(n_train, generator=generator).to(device)
        running = torch.zeros((), device=device)

        for i in range(0, n_train, config.batch_size):
            idx = order[i:i + config.batch_size]

            optimizer.zero_grad(set_to_none=True)
            z_T = euler_rollout(net, z[idx], T)         # differentiable through all T steps
            loss = _mse_per_example(z_T, target_p[idx])
            loss.backward()
            nn.utils.clip_grad_norm_(net.parameters(), config.max_grad_norm)
            optimizer.step()

            running += loss.detach() * idx.numel()

        history.append((running / n_train).item())

    return net, history, time.perf_counter() - start


@torch.no_grad()
def evaluate_flow(
    net: VelocityNet,
    test_x: torch.Tensor,
    test_y: torch.Tensor,
    prototypes: torch.Tensor,
    T_values: list[int],
    device: str = "cuda",
    normalize: bool = True,
) -> tuple[dict[int, float], dict[int, torch.Tensor]]:
    """Transport the test features and classify them, for each requested ``T``.

    Predictions are returned alongside the accuracies so later steps can build confusion
    matrices and per-class analyses without re-running any rollout.

    Args:
        T_values: e.g. ``[4, 12]``. A standard-FM model is legitimately evaluated at several
            ``T``; a rolled-out model should only be evaluated at the ``T`` it was trained
            with.

    Returns:
        ``({T: accuracy}, {T: predictions})``.
    """
    net.eval()
    # Must match how the model was trained - evaluating a raw-feature model on normalized
    # inputs (or vice versa) would compare two different things.
    z = (l2_normalize(test_x) if normalize else test_x).to(device)
    y = test_y.to(device)
    p = prototypes.to(device)

    accuracies: dict[int, float] = {}
    predictions: dict[int, torch.Tensor] = {}

    for T in T_values:
        z_T = euler_rollout(net, z, T)
        preds = classify_by_prototype(z_T, p)
        accuracies[T] = (preds == y).float().mean().item()
        predictions[T] = preds.cpu()

    return accuracies, predictions
